name: .NET Core Desktop

on:
  push:
    branches: ["obs-ws5.0"]
  pull_request:
    branches: ["obs-ws5.0"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on:
      windows-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MidiControl.sln

    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore $env:Solution_Name
        
      - name: Replace Secrets
        run: |
          sed -i "s/TWITCH_CLIENTSECRET/${{secrets.TWITCH_CLIENTSECRET}}/g" "MidiControl/App.config" &&
          sed -i "s/TWITCH_CLIENTID/${{secrets.TWITCH_CLIENTID}}/g" "MidiControl/App.config"
        shell: bash
      
      - name: Resource generation
        run: |
          Set-Location -Path "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\"
          .\ResGen.exe "D:\a\MidiControl\MidiControl\MidiControl\Properties\Resources.resx" /useSourcePath /str:csharp,MidiControl.Properties
        shell: powershell
        
      - name: Build app for Release
        run: msbuild $env:Solution_Name -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "setup.iss"
        shell: cmd

      - uses: actions/upload-artifact@v3
        with:
          path: "Output/MIDIControl * Setup.exe"
